language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-lean-mean' ]; then cd .. && eval "mv $currentfolder generator-lean-mean" && cd generator-lean-mean; fi

